#pragma once

#include <wayland-client.h>
#include <wayland-cursor.h>
#include <wpe/wpe-platform.h>

/* Protocol headers generated by wayland-scanner */
#include "protocols/xdg-shell-client-protocol.h"
#include "protocols/linux-dmabuf-v1-client-protocol.h"

typedef struct {
    struct wl_display        *display;
    struct wl_registry       *registry;
    struct wl_compositor     *compositor;
    struct wl_subcompositor  *subcompositor;
    struct wl_shm            *shm;
    struct wl_seat           *seat;
    struct wl_pointer        *pointer;
    struct wl_keyboard       *keyboard;
    struct xdg_wm_base       *wm_base;
    struct zwp_linux_dmabuf_v1 *dmabuf;

    /* cursors */
    struct wl_cursor_theme   *cursor_theme;
    struct wl_cursor         *cursor_default;
    struct wl_cursor         *cursor_text;
    struct wl_cursor         *cursor_pointer;
    struct wl_surface        *cursor_surface;
} WaylandState;

/* Open our own Wayland connection and bind all needed globals.
 * This replaces the old wayland_init() that borrowed WPE's connection. */
void wayland_connect(WaylandState *wl);
void wayland_finish(WaylandState *wl);
void wayland_set_cursor(WaylandState *wl, struct wl_pointer *ptr,
    uint32_t serial, const char *name);
